server:
  port: 8082
message: Producer configuration server is alive!
logging:
  level:
    org:
      springframework: DEBUG

# h2
spring:
  h2:
    console:
      enable: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:carService
    username: sa
    password: 
