server:
  port: ${PORT:8882}
message: Producer configuration server is alive!
logging:
  level:
    org:
      springframework: DEBUG

# h2
spring:
  h2:
    console:
      enable: true
spring:
  h2:
    console:
      path: /h2
spring:
  datasource:
    url: jdbc:h2:mem:carService
spring:
  datasource:
    username: sa
spring:
  datasource:
    password: 
