server:
  port: 8081
message: Producer configuration server is alive!
logging:
  level:
    org:
      springframework: DEBUG

# h2
spring:
  h2:
    console:
      enable: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:userAuth
    username: sa
    password: 

# Eureka
eureka:
  client:
    fetch-register: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
